// These sequences are core in the sense that any other sequence may depend on them but none of them can depend on others
pub mod arithmetic;
pub mod bernoulli_numbers;
pub mod composite;
pub mod constant;
pub mod continued_fraction;
pub mod digital_sum;
pub mod divisor;
pub mod exponential;
pub mod factorial;
pub mod geometric;
pub mod integer;
pub mod natural;
pub mod nth_powers;
pub mod parity;
pub mod pascal;
pub mod powers;
pub mod primality_utils;
pub mod prime;
pub mod rational_digits;
pub mod rationals;
pub mod recurrence;
pub mod roots;
pub mod transforms;

// Easy imports from other places
pub use arithmetic::*;
pub use bernoulli_numbers::*;
pub use composite::*;
pub use constant::*;
pub use continued_fraction::*;
pub use digital_sum::*;
pub use divisor::*;
pub use exponential::*;
pub use factorial::*;
pub use geometric::*;
pub use integer::*;
pub use natural::*;
pub use nth_powers::*;
pub use parity::*;
pub use pascal::*;
pub use powers::*;
pub use primality_utils::*;
pub use prime::*;
pub use rational_digits::*;
pub use rationals::*;
pub use recurrence::*;
pub use roots::*;
pub use transforms::*;

use num::{BigInt, FromPrimitive};
use std::cell::LazyCell;
pub const TWO: LazyCell<BigInt> = LazyCell::new(|| BigInt::from_i32(2).unwrap());
pub const NEG_TWO: LazyCell<BigInt> = LazyCell::new(|| BigInt::from_i32(-2).unwrap());
