use crate::Number;
use num::{BigInt, CheckedAdd, CheckedMul, CheckedSub, Integer, One, integer::gcd};

/// All primitive Pythagorean triples generated by Euclid's formula with sides sorted in increasing order.
///
/// ```text
/// (3, 4, 5), (5, 12, 13), (8, 15, 17)...
/// ```
pub struct PythagoreanTriples<T> {
    m: T,
    n: T,
}

impl PythagoreanTriples<Number> {
    pub fn new() -> Self {
        Self { m: 2, n: 1 }
    }
}

impl PythagoreanTriples<BigInt> {
    pub fn new_big() -> Self {
        Self {
            m: BigInt::from(2),
            n: BigInt::one(),
        }
    }
}

impl<T: CheckedAdd + CheckedMul + CheckedSub + Clone + Integer> Iterator for PythagoreanTriples<T> {
    type Item = (T, T, T);

    fn next(&mut self) -> Option<Self::Item> {
        // Generate the sorted array
        let m2 = self.m.checked_mul(&self.m)?;
        let n2 = self.n.checked_mul(&self.n)?;
        let a = m2.checked_add(&n2)?;
        let b = self
            .m
            .checked_mul(&self.n)?
            .checked_mul(&(T::one() + T::one()))?;
        let c = m2.checked_sub(&n2)?;
        let mut arr = [a, b, c];
        arr.sort();

        // Find the next pair
        // Requirements:
        // m > n > 0
        // gcd(m,n) = 0
        // one of m,n even
        loop {
            if self.m > self.n {
                self.n = self.n.checked_add(&T::one())?;
            }
            if self.m == self.n {
                self.m = self.m.checked_add(&T::one())?;
                self.n = T::one();
            }
            if gcd(self.m.clone(), self.n.clone()) == T::one()
                && (self.m.is_even() || self.n.is_even())
            {
                break;
            }
        }

        Some((arr[0].clone(), arr[1].clone(), arr[2].clone()))
    }
}

crate::print_sequences!(
    PythagoreanTriples::new(), 100, "{:?}", "\n";
);
